'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/playcourt/button';

const steps = ['Cơ bản', 'Sân & giờ', 'Người chơi', 'Xác nhận'];
export default function CreateMatchPage() {
  const [step, setStep] = useState(0); const [sport, setSport] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  useEffect(() => { const id = window.setTimeout(() => setSaved(true), 800); return () => window.clearTimeout(id); }, [sport, step]);
  const next = () => { if (step === 0 && !sport) { setError('Vui lòng chọn môn thể thao trước khi tiếp tục.'); return; } setError(''); setStep((current) => Math.min(current + 1, 3)); };
  return <section className="mx-auto max-w-3xl px-4 py-10"><p className="font-mono text-xs uppercase tracking-[.16em] text-[var(--pc-mute)]">Create match</p><h1 className="mt-2 text-3xl font-semibold text-[var(--pc-ink)]">Tạo trận đấu</h1><div className="mt-6 flex gap-2">{steps.map((label, index) => <div key={label} className={`flex-1 border-t-2 pt-2 text-xs ${index <= step ? 'border-[var(--pc-green-700)] text-[var(--pc-ink)]' : 'border-[var(--pc-hairline)] text-[var(--pc-mute)]'}`}>Bước {index + 1}: {label}</div>)}</div><div className="mt-8 rounded-xl border border-[var(--pc-hairline)] bg-white p-6">{step === 0 && <><h2 className="font-semibold text-[var(--pc-ink)]">Chọn môn thể thao</h2><div className="mt-4 flex gap-3">{['Cầu lông', 'Pickleball', 'Tennis'].map((item) => <button type="button" key={item} onClick={() => setSport(item)} className={`rounded-md border px-4 py-2 text-sm ${sport === item ? 'border-[var(--pc-green-700)] bg-[var(--pc-green-50)]' : 'border-[var(--pc-hairline)]'}`}>{item}</button>)}</div></>}{step === 1 && <><h2 className="font-semibold text-[var(--pc-ink)]">Bước 2: Sân & giờ</h2><p className="mt-2 text-sm text-[var(--pc-body)]">PlayCourt Phú Nhuận · Thứ bảy, 08:00</p></>}{step === 2 && <><h2 className="font-semibold text-[var(--pc-ink)]">Bước 3: Người chơi</h2><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" defaultChecked /> Tự động duyệt thành viên</label></>}{step === 3 && <><h2 className="font-semibold text-[var(--pc-ink)]">Bước 4: Xác nhận</h2><p className="mt-2 text-sm text-[var(--pc-body)]">{sport} · Đã sẵn sàng công khai trận đấu.</p></>} {error && <p role="alert" className="mt-4 text-sm text-[var(--pc-error-deep)]">{error}</p>}<div className="mt-7 flex justify-between"><Button variant="Secondary" type="button" disabled={!step} onClick={() => setStep((current) => current - 1)}>Quay lại</Button><Button type="button" onClick={next}>{step === 3 ? 'Đăng trận' : 'Tiếp tục'}</Button></div></div><p className="mt-3 text-right text-xs text-[var(--pc-mute)]">{saved ? 'Đã lưu bản nháp' : 'Đang lưu bản nháp…'}</p></section>;
}
